import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import { calling } from '../utils/contractInteraction';
import { useEthersSigner } from '../../hooks/useEthersSigner';

const Home: NextPage = () => {
  const [amountToMint, setAmountToMint] = useState<number>(0);
  const signer = useEthersSigner();
  // Handle input change from the keyboard
  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = parseInt(event.target.value, 10);
    if (!isNaN(value)) {
      setAmountToMint(value);
    }
  };

  const handleSetAmount = () => {
    alert(`Amount set to ${amountToMint}`);
  };

  const handleMintTokens = async () => {
    console.log('Mint Tokens button clicked');
    console.log(signer);
    if (amountToMint > 0 && signer) {
      const actualSigner = await signer.getSignerAsync();
      calling(amountToMint, actualSigner);
    } else {
      alert('Please set a valid amount to mint.');
    }
  };

  return (
    <div className={styles.container} style={{ fontFamily: "'Roboto', sans-serif", backgroundColor: '#f0f4f8', padding: '20px' }}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main} style={{ textAlign: 'center' }}>
        <ConnectButton />

        <h1 className={styles.title} style={{ color: '#0070f3', margin: '20px 0' }}>
          Welcome to <a href="" style={{ color: '#0070f3', textDecoration: 'none' }}>Nosark</a>
        </h1>

        <p className={styles.description} style={{ color: '#333', fontSize: '1.2rem', marginBottom: '30px' }}>
          Get started by connecting your wallet and minting tokens.
        </p>

        <div className={styles.grid} style={{ display: 'flex', justifyContent: 'center', gap: '20px', marginBottom: '30px' }}>
          <div style={{ backgroundColor: '#fff', padding: '20px', borderRadius: '10px', boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)', width: '300px' }}>
            <h2 style={{ color: '#0070f3' }}>Why Mint Tokens?</h2>
            <p style={{ color: '#555' }}>Minting tokens allows you to participate in our ecosystem, providing access to exclusive features and benefits.</p>
          </div>
          <div style={{ backgroundColor: '#fff', padding: '20px', borderRadius: '10px', boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)', width: '300px' }}>
            <h2 style={{ color: '#0070f3' }}>Secure and Reliable</h2>
            <p style={{ color: '#555' }}>Our platform ensures secure transactions and reliable services, backed by blockchain technology.</p>
          </div>
        </div>

        {/* Color Palette Image */}
        <div style={{ marginBottom: '30px' }}>
          <img src="/path/to/your/color-palette.png" alt="Color Palette" style={{ maxWidth: '100%', borderRadius: '10px', boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)' }} />
        </div>

        {/* New input and buttons */}
        <input
          type="number"
          placeholder="Enter amount to mint"
          onChange={handleInputChange}
          style={{ margin: '10px', padding: '10px', borderRadius: '5px', border: '1px solid #ccc', width: '200px' }}
          onKeyPress={(event) => {
            if (event.key === 'Enter') {
              handleSetAmount();
            }
          }}
        />
        <div style={{ marginTop: '20px' }}>
          <button onClick={handleSetAmount} style={{ backgroundColor: '#ff0000', color: 'white', border: 'none', padding: '10px 20px', margin: '5px', borderRadius: '5px', cursor: 'pointer', transition: 'background-color 0.3s' }}>
            Set Amount
          </button>
          <button onClick={handleMintTokens} style={{ backgroundColor: '#ff0000', color: 'white', border: 'none', padding: '10px 20px', margin: '5px', borderRadius: '5px', cursor: 'pointer', transition: 'background-color 0.3s' }}>
            Mint Tokens
          </button>
        </div>
      </main>

      <footer className={styles.footer} style={{ backgroundColor: '#0070f3', color: 'white', padding: '10px', textAlign: 'center' }}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank" style={{ color: 'white', textDecoration: 'none' }}>
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;