import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import { calling } from '../utils/contractInteraction';
import { useEthersSigner } from '../../hooks/useEthersSigner';
import { motion } from 'framer-motion';

const Home: NextPage = () => {
  const [amountToMint, setAmountToMint] = useState<number>(0);
  const signer = useEthersSigner();

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = parseInt(event.target.value, 10);
    if (!isNaN(value)) {
      setAmountToMint(value);
    }
  };

  const handleMintTokens = async () => {
    if (amountToMint > 0 && signer) {
      const actualSigner = await signer.getSignerAsync();
      calling(amountToMint, actualSigner);
    } else {
      alert('Please set a valid amount to mint.');
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet" />
      </Head>

      <div style={{
        backgroundImage: "url('https://via.placeholder.com/1800')", // Placeholder image for testing
        backgroundSize: 'cover', /* Cover the entire section */
        height: '100vh', /* Full height */
        width: '100%' /* Full width */
      }}>
        <motion.header
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1 }}
          className={styles.header}
        >
          <h1 className={styles.headerTitle}>Welcome to the Future of Token Minting!</h1>
          <p className={styles.subheading}>Join us in revolutionizing the blockchain experience.</p>
        </motion.header>

        <main className={styles.main} style={{ color: '#FFFFFF' }}>
          <ConnectButton />

          <h1 className={styles.title} style={{ color: '#FF6F61' }}>
            Welcome to <a href="" className={styles.link} style={{ color: '#FF6F61' }}>Nosark</a>
          </h1>

          <p className={styles.description}>
            Get started by connecting your wallet and minting tokens.
          </p>

          <input
            type="number"
            placeholder="Enter amount to mint"
            onChange={handleInputChange}
            className={styles.input}
            style={{ borderColor: '#FF6F61' }}
          />
          <div className={styles.buttonContainer}>
            <motion.button
              whileHover={{ scale: 1.05, backgroundColor: '#FF4D4D' }}
              onClick={handleMintTokens}
              className={styles.button}
              style={{ backgroundColor: '#FF6F61', color: '#FFFFFF' }}
            >
              Mint Tokens
            </motion.button>
          </div>
        </main>

        <footer className={styles.footer} style={{ backgroundColor: '#FF6F61', color: '#FFFFFF' }}>
          <p>Explore more at <a href="https://example.com" className={styles.footerLink} style={{ color: '#FFCC00' }}>Our Website</a></p>
          <p>Stay connected: <a href="https://twitter.com" className={styles.footerLink} style={{ color: '#FFCC00' }}>Twitter</a> | <a href="https://discord.com" className={styles.footerLink} style={{ color: '#FFCC00' }}>Discord</a></p>
        </footer>
      </div>
    </div>
  );
};

export default Home;